/* WHAT A msgId PROMISES, ON BOTH OF THE CLIPS THIS ENGINE STORES.
 *
 * A msgId is the app's handle on a piece of audio: it draws a tick from one and
 * a play button from the other. Both are claims that the clip EXISTS, and this
 * file is about the engine handing out a msgId when it does not. The two halves
 * are the user's own recording and a spoken reply's TTS clip; they fail for the
 * same reason, through the same cacheAudio, and they cost different things.
 *
 * WHY THIS FILE EXISTS
 *
 * The app draws exactly one tick on a voice-note bubble and that tick means
 * "your recording cannot be lost". It is drawn when /user-audio answers with a
 * msgId. The handler used to answer the moment the bytes were in this process's
 * memory: cacheAudio fired `Bun.write(...).catch(console.error)` and never
 * waited for it, so the tick really meant "a write has been queued". Measured
 * against the live engine with a real clip, the response came at 23.24ms and the
 * file appeared at 23.27ms, which is why nobody ever saw it: it wins in
 * practice. It is not guaranteed, the failure went to a console the phone cannot
 * read, and once the hot cache evicts that msgId the only copy of the user's own
 * recording is gone.
 *
 * A user's recording is the one piece of audio in this system with no second
 * copy anywhere. The phone hands it over and forgets it.
 *
 * HOW THE FAILURE IS PRODUCED: by taking write permission off this test's own
 * audio directory, so the write fails for the same reason a full or read-only
 * disk would fail. No stub, no injected fault: the real Bun.write really does
 * refuse.
 *
 * -------------------------------------------------------------------------
 * ON REAL CAPTURES, AND WHY MOST OF THIS FILE NO LONGER DEMANDS ONE
 *
 * The old version of this file posted a REAL `.webm` out of <repo>/.run/audio
 * and refused to settle for generated audio, on the argument that this is a
 * test about a recording. That refusal is kept, and it is kept HONEST: the
 * capture-only tests below are `test.skipIf`-ed and say so loudly when the
 * store is empty (which is the state of every fresh checkout and of this box),
 * instead of failing seven tests for a reason that has nothing to do with the
 * engine.
 *
 * What DOES need real codec bytes is exactly one thing, and it is stated where
 * it is asserted: that the stored file is a decodable RECORDING, which is what
 * ffprobe reads a duration off and what the container/extension mapping is
 * for. Everything else here -- the ack ordering, the on-disk-before-announce
 * rule, msgId integrity, the traversal refusal, serving -- is about bytes
 * arriving and bytes coming back, and generated bytes prove it exactly as well.
 * Those run always.
 *
 * Nothing here writes to a real store: the wiring gets a throwaway data dir.
 */

import { test, expect, beforeAll, afterAll, afterEach } from "bun:test";
import { existsSync } from "node:fs";
import { chmod, readdir, readFile, rm } from "node:fs/promises";
import { join } from "node:path";

import { audioDirFor, audioDurationS, audioPath, resetForTest as resetClips } from "./clips.ts";
import { agentAudioDir, agentChatsDir, agentDir } from "../storage/datadir.ts";
import { mkdirPrivate } from "../../../shared/runfiles.ts";
import { initTts, resetForTest as resetTts } from "../voice/tts.ts";
import { onSpeak } from "./reply.ts";
import { mediaRoutes } from "../routes/media.ts";
import { broadcast } from "../transport/wire.ts";
import { persistPatch, restoredChats, sessionByHandle, voiceFor } from "../sessions/session-state.ts";
import { PANE } from "../test-utils/fake-herdr.ts";
import { fakeVoice, type FakeVoice } from "../test-utils/fake-voice.ts";
import { serveRoutes, type ServedRoutes } from "../test-utils/serve-routes.ts";
import { until } from "../test-utils/wait.ts";
import { wireCore, type FakeClient, type WireCore } from "../test-utils/wire-core.ts";

/* ------------------------------------------------------- the real capture, if any
 *
 * Derived the way e2e/mutation/verified-run.sh derives it: --git-common-dir
 * points at the main checkout's .git from inside any linked worktree, so the
 * store is found whichever tree the suite is running from. READ ONLY; nothing
 * in this file writes to it or deletes from it. */
/* `Uint8Array<ArrayBuffer>` for the same reason `generated` says below: the
 * bare `Uint8Array` is Uint8Array<ArrayBufferLike> under TS 5.7, and every
 * comparison here is against bytes read out of an ArrayBuffer. */
async function realCapture(): Promise<Uint8Array<ArrayBuffer> | null> {
  const root = process.env.CYC_ENGINE_ROOT ??
    (await Bun.$`git rev-parse --path-format=absolute --git-common-dir`.cwd(import.meta.dir)
      .quiet().then((r) => join(r.stdout.toString().trim(), "..")).catch(() => ""));
  if (!root) return null;
  const dir = join(root, ".run", "audio");
  const webm = (await readdir(dir).catch(() => [] as string[]))
    .filter((n) => n.endsWith(".webm")).sort();
  if (!webm.length) {
    console.warn(
      `[audio.test] SKIPPING the real-capture tests: no .webm in ${dir}.\n` +
      "  Two assertions in this file are about a RECORDING rather than about bytes -- that " +
      "the stored clip is decodable (ffprobe reads a duration off it) and that a real " +
      "MediaRecorder container round-trips byte for byte through its own extension. " +
      "Generated audio cannot make either claim honestly, so they are skipped rather than " +
      "weakened. Record one from the app (press and hold the mic), or point CYC_ENGINE_ROOT " +
      "at a checkout whose .run/audio has one. Everything else in this file still runs.");
    return null;
  }
  // deterministic pick: the smallest non-empty one, so the test moves the fewest bytes
  let best = { name: webm[0], size: Infinity };
  for (const n of webm) {
    const size = Bun.file(join(dir, n)).size;
    if (size > 0 && size < best.size) best = { name: n, size };
  }
  return new Uint8Array(await readFile(join(dir, best.name)));
}

const CAPTURE = await realCapture();
const withCapture = test.skipIf(!CAPTURE);

/** Bytes that are NOT a recording: enough to prove a byte pipeline, and
 *  deliberately not enough to prove anything about audio. */
/* `Uint8Array<ArrayBuffer>`, not the bare `Uint8Array`: TS 5.7 reads the bare
 * name as Uint8Array<ArrayBufferLike>, and every comparison below is against
 * `new Uint8Array(await res.arrayBuffer())`, which is over a plain ArrayBuffer.
 * Two spellings of the same bytes will not compare. */
function generated(n = 4096): Uint8Array<ArrayBuffer> {
  const b = new Uint8Array(n);
  for (let i = 0; i < n; i++) b[i] = (i * 37 + 11) & 0xff;
  return b;
}

/* ------------------------------------------------------------------ the wiring */

let core: WireCore;
let voice: FakeVoice;
let http: ServedRoutes;
let client: FakeClient;
/** msgId -> was the clip on disk at the instant the `say` frame went out */
const onDiskAtSay = new Map<string, boolean>();

/* A DISK THAT WILL NOT TAKE THE CLIP, produced the way one really refuses.
 *
 * Freezing the audio directory itself does nothing: cacheAudio calls
 * mkdirPrivate() first, and mkdirPrivate chmods the leaf back to 0700 (it has
 * to: a recursive mkdir only sets the last component, and the umask on these
 * hosts is 0002). So the directory is REMOVED and its parent frozen, which is
 * the same thing a read-only or full disk does from inside cacheAudio: the
 * clip's directory cannot be made, and the write never happens.
 *
 * The parent is chosen so that only the CLIP's path is blocked. The words take
 * a different path and must still land, which is the whole distinction the TTS
 * half of this file draws. */
let locked: string | null = null;
async function freezeAudioDir(dir: string, parent: string): Promise<void> {
  await rm(dir, { recursive: true, force: true });
  await chmod(parent, 0o555);
  locked = parent;
}

beforeAll(async () => {
  /* "frames" is the layer that wires reply.ts, which is the speak half. The
   * clip store, the chat log and the session graph come with it; there is no
   * engine process, no Bun.serve for the wire and no voice engine but the fake
   * one below. */
  core = await wireCore({ with: ["frames"] });
  await until(() => core.sessions.size === 1, { what: "the pane to reconcile" });

  voice = fakeVoice({ ttsBytes: new Uint8Array([0xff, 0xfb, 0x90, 0x64, 0x00, 0x00]) });
  /* wireCore points tts.ts at a voice engine that REFUSES, so a seam test that
   * reaches for speech by accident fails loudly rather than dialling his actual
   * kokoro. This file is about speech, so it re-wires that one seam and nothing
   * else: same deps, same modules, the fake upstream instead of the refusal. */
  initTts({
    voiceUrl: () => voice.voiceUrl(),
    voiceFor: (id) => voiceFor(id),
    persistPatch: (id, mts, set, unset) => persistPatch(id, mts, set, unset),
    /* THE ONE SYNCHRONOUS OBSERVATION IN THIS FILE, and the only place "the
     * clip was on disk BEFORE it was announced" can honestly be asked: the say
     * frame is the announcement, and by the time a test could read the frame off
     * a client the write has long since finished either way. Checked here, in
     * the same tick the engine makes the claim. */
    broadcast: (m) => {
      const f = m as { t?: string; msgId?: string };
      if (f.t === "say" && f.msgId) {
        onDiskAtSay.set(f.msgId, existsSync(audioPath(f.msgId, "audio/mpeg")));
      }
      broadcast(m);
    },
    restoredChats: () => restoredChats,
    clock: core.clock,
  });

  http = serveRoutes({ groups: [mediaRoutes], ctx: { uploads: core.uploads! } });
  client = core.client({ attach: PANE });
  client.sock.data.sessionId = PANE; // the socket a session's MCP replies arrive on
});

afterAll(async () => {
  if (locked) { await chmod(locked, 0o755).catch(() => {}); locked = null; }
  http?.stop();
  voice?.stop();
  await core?.stop();
  resetTts();
  resetClips();
});

afterEach(async () => {
  // the permission goes back BEFORE anything else, or the next test writes into
  // a directory the previous one froze
  if (locked) { await chmod(locked, 0o755).catch(() => {}); locked = null; }
  client.clear();
  voice.reset();
});

const stagingAudio = () => join(core.dir, "staging", "audio");
const post = (bytes: Uint8Array, type = "audio/webm", cid?: string) =>
  http.fetch(`/user-audio${cid ? `?cid=${cid}` : ""}`, {
    method: "POST", headers: { "content-type": type }, body: bytes as unknown as BodyInit,
  });

/* ----------------------------------------------------- the user's own recording */

test("a voice note the engine could not save is not answered with a msgId", async () => {
  await freezeAudioDir(stagingAudio(), join(core.dir, "staging"));

  const res = await post(generated());
  const body = (await res.json().catch(() => ({}))) as { msgId?: unknown };

  expect(body.msgId,
    "the engine answered a voice note it could not put on disk WITH a msgId. That msgId is " +
    "what the app draws its single tick from, and the tick says the recording cannot be " +
    "lost. The bytes are in this process's memory only, the phone has already forgotten " +
    "them, and the next eviction from the hot cache is the end of the user's recording.")
    .toBeUndefined();
  expect(res.ok,
    "a voice note that never reached the disk was answered with a success status, so the app " +
    "has no way to know not to draw the tick (client.ts uploadAudio throws on any non-ok " +
    "status and on that path only).").toBe(false);
  expect(res.status).toBe(500);

  // it failed for the reason this test set up, not somewhere else on the way in
  const failed = http.logs.filter((l) => l.event === "user-audio.persist-failed");
  expect(failed.length,
    "no persist failure was logged, so the 500 above may not be the write at all")
    .toBe(1);
  expect(String(failed[0].fields.why)).toContain("no msgId is handed out");

  // and nothing was left behind claiming to be that clip
  expect(await readdir(stagingAudio()).catch(() => [] as string[]),
    "the failed write left a file in the audio directory").toEqual([]);
});

test("a voice note the engine did save is on disk before the msgId is sent", async () => {
  const bytes = generated(8192);
  const res = await post(bytes);
  expect(res.ok, "a healthy engine refused a voice note").toBe(true);
  const { msgId } = (await res.json()) as { msgId: string };
  expect(typeof msgId, "no msgId came back for a note that should have been saved").toBe("string");

  /* NO WAIT, NO RETRY LOOP, deliberately: the claim is that the response is sent
   * AFTER the write completes, so the file is there on the first look. A poll
   * here would let the old un-awaited write pass this too. */
  const path = join(stagingAudio(), `${msgId}.webm`);
  expect(await Bun.file(path).exists(),
    `the msgId came back but ${path} does not exist yet, so the tick the app draws from it ` +
    "is ahead of the disk").toBe(true);
  expect(new Uint8Array(await readFile(path)).byteLength,
    "the clip on disk is not the clip that was posted").toBe(bytes.byteLength);

  // and it plays back: the route the app's <audio> element uses returns it
  const clip = await http.fetch(`/audio/${msgId}.mp3`);
  expect(clip.ok, "the saved clip does not serve").toBe(true);
  expect(new Uint8Array(await clip.arrayBuffer())).toEqual(bytes);
  /* The .mp3 suffix is cosmetic; the content-type is what the element decodes
   * by, and it is the one the recording arrived as. */
  expect(clip.headers.get("content-type")).toBe("audio/webm");
});

test("the msgId that comes back is the one the clip is filed under, and nothing else serves", async () => {
  /* msgId INTEGRITY on the upload side: the id is minted here, so the only way
   * it can be wrong is by naming a file that is not this recording. Two clips,
   * posted back to back, each served by its own id. */
  const a = generated(1024);
  const b = generated(2048);
  const idA = ((await (await post(a)).json()) as { msgId: string }).msgId;
  const idB = ((await (await post(b)).json()) as { msgId: string }).msgId;
  expect(idA).not.toBe(idB);
  expect(new Uint8Array(await (await http.fetch(`/audio/${idA}.mp3`)).arrayBuffer())).toEqual(a);
  expect(new Uint8Array(await (await http.fetch(`/audio/${idB}.mp3`)).arrayBuffer())).toEqual(b);

  // an id this engine never minted is a 404, not somebody else's clip
  expect((await http.fetch(`/audio/${crypto.randomUUID()}.mp3`)).status).toBe(404);
});

test("a msgId cannot climb out of the audio directory on the way to /audio", async () => {
  /* The READ twin of the write filter below. clipOnDisk/audioFromDisk paste the
   * msgId straight into a path, and it is a raw wire string. The route's own
   * pattern stops a slash, and safeCid stops the rest; both are asserted rather
   * than assumed, because the answer here gates behaviour and not just a file
   * read (see rescue.test.ts, where it decides whether a note survives). */
  expect((await http.fetch("/audio/..%2Foutside.mp3")).status).not.toBe(200);
  expect((await http.fetch("/audio/../outside.mp3")).status).not.toBe(200);
});

withCapture("a REAL captured note round-trips byte for byte, in its own container", async () => {
  /* THE STRONG FORM, and the one that needs an actual recording: a
   * MediaRecorder webm goes in, is filed under the extension its mime maps to
   * (not the cosmetic .mp3 the URL wears), and comes back byte for byte with
   * the content-type it was recorded as. Generated bytes exercise the same
   * lines; only a capture proves the mapping is right for the thing the phone
   * actually produces. */
  const res = await post(CAPTURE!);
  expect(res.ok).toBe(true);
  const { msgId } = (await res.json()) as { msgId: string };
  const onDisk = new Uint8Array(await readFile(join(stagingAudio(), `${msgId}.webm`)));
  expect(onDisk.byteLength).toBe(CAPTURE!.byteLength);
  expect(onDisk).toEqual(CAPTURE!);

  const served = await http.fetch(`/audio/${msgId}.mp3`);
  expect(served.headers.get("content-type")).toBe("audio/webm");
  expect(new Uint8Array(await served.arrayBuffer())).toEqual(CAPTURE!);
});

withCapture("the stored capture is a decodable recording, not merely the bytes posted", async () => {
  /* THE ONE ASSERTION IN THIS FILE THAT GENERATED AUDIO CANNOT MAKE. A voice
   * bubble's clock comes from audioDurationS, which is ffprobe over the stored
   * path: it answers 0 for anything that is not really audio, and 0 is also
   * what "the file is not there" looks like. Only a real capture can tell those
   * two apart. */
  const { msgId } = (await (await post(CAPTURE!)).json()) as { msgId: string };
  const seconds = await audioDurationS(join(stagingAudio(), `${msgId}.webm`));
  expect(seconds,
    "ffprobe could not read a duration off the stored capture, so what landed on disk is " +
    "not the recording that was posted").toBeGreaterThan(0);
});

/* ------------------------------------------------------------- the OTHER clip
 *
 * A spoken reply's audio is written by the same cacheAudio, and synthesize()
 * used to swallow a persist failure on the argument that a TTS clip is
 * re-derivable from its text. Nothing in this system re-derives one. What
 * actually happens on a failed write is that ffprobe reads a file that is not
 * there, returns 0 rather than throwing, so the row goes out carrying a msgId
 * whose /audio/<msgId>.mp3 exists only in this process's memory. It plays until
 * the engine restarts and 404s afterwards.
 *
 * The assertion is therefore not "the reply is refused". A reply with no voice
 * is a reply, and the words must still arrive. It is that the engine does not
 * ADVERTISE a clip it could not keep.
 */

/** The persisted row for one spoken reply, after the patches. */
const rowFor = (text: string) => sessionByHandle(PANE)!.chat.find((m) => m.text === text);

test("a spoken reply the engine could not save is not announced as playable", async () => {
  const TEXT = "the disk is refusing writes right now";
  /* The same disk that will not take a voice note will not take a TTS clip. The
   * agent's CHAT directory is made first and left alone, so the words have
   * somewhere to go and the only thing that cannot be written is the clip. */
  const aid = sessionByHandle(PANE)!.id;
  await mkdirPrivate(agentChatsDir(aid));
  await freezeAudioDir(agentAudioDir(aid), agentDir(aid));

  await onSpeak(client.sock, { t: "speak", text: TEXT });
  await until(() => client.of("said").length > 0, { what: "the speak tool's ack" });

  /* THE WORDS ARE NOT THE THING AT RISK, and losing them would be a worse bug
   * than the one this test is about. */
  const chat = client.of("chat").find((f) => f.role === "claude" && f.text === TEXT);
  expect(chat, "the reply never reached the page at all. A TTS clip that cannot be written " +
    "must still be delivered as written words: the speech is what is lost, not the answer.")
    .toBeTruthy();

  // synthesis runs behind the ack, so wait for its retraction rather than
  // assuming it happened before the chat frame
  await until(() => rowFor(TEXT)?.msgId === undefined,
    { what: "the failed persist to un-claim the msgId" });

  expect(client.of("say").some((f) => f.text === TEXT),
    "the engine broadcast a `say` frame for a clip it could not put on disk. Every attached " +
    "device is then told to fetch /audio/<msgId>.mp3, which exists only in this process's " +
    "memory: it plays until the engine restarts and 404s for ever afterwards.").toBe(false);

  /* And the row agrees, so a later replay cannot resurrect the claim. */
  expect(rowFor(TEXT)!.msgId,
    "the chat log kept a msgId for a clip that is not on disk, so every future attach replays " +
    "a playable-looking bubble that 404s").toBeUndefined();
  expect(rowFor(TEXT)!.growing, "the row was left stuck growing").toBeUndefined();
});

test("a spoken reply the engine did save is announced, and serves", async () => {
  /* THE OTHER HALF, and the reason the test above cannot be passed by refusing
   * to speak at all. A healthy engine still announces its clip and still serves
   * it, so "no say frame" is a statement about the failure and not about the
   * feature. */
  const TEXT = "this one goes to disk";
  await onSpeak(client.sock, { t: "speak", text: TEXT });
  const say = await untilSay(TEXT);

  expect(say.msgId, "the announced clip has no id").toBeTruthy();
  const path = audioPath(String(say.msgId), "audio/mpeg");
  expect(await Bun.file(path).exists(), "the announced clip is in memory only").toBe(true);
  /* AND IT WAS THERE BEFORE THE ANNOUNCEMENT, not a moment after it. The `say`
   * tells every attached device to fetch /audio/<msgId>.mp3; announcing first
   * and writing second is a window in which every one of them 404s, and it is
   * the same window the failed-persist case above turns into a permanent one. */
  expect(onDiskAtSay.get(String(say.msgId)),
    "the clip was announced before it was on disk").toBe(true);
  /* Filed under its AGENT, not in staging: the row was logged before the clip
   * was made, so the blob index already knew whose it was. */
  expect(audioDirFor(String(say.msgId))).toContain("/agents/");

  const clip = await http.fetch(`/audio/${say.msgId}.mp3`);
  expect(clip.ok, "the announced clip does not serve").toBe(true);
  expect(new Uint8Array(await clip.arrayBuffer())).toEqual(new Uint8Array(voice.ttsBytes));
});

test("a speak frame's msgId cannot put the TTS clip outside the audio directory", async () => {
  /* The msgId is also a PATH. cacheAudio writes the TTS bytes to
   * audioPath(msgId), and audioDurationS hands that same string to ffprobe as
   * an argv entry. onReply took it straight off the wire:
   * `String(m.msgId ?? crypto.randomUUID())`. A read that escapes finds
   * whatever happens to be there; a write that escapes puts caller-chosen bytes
   * at a caller-chosen path and then runs a subprocess on it.
   *
   * WHAT IS ASSERTED IS NOT "THE REPLY IS REFUSED". A reply is something he is
   * owed and an agent has already returned from; dropping one to punish a field
   * nothing depends on is the wrong trade. So the bad id is replaced and the
   * reply goes out. Both halves are asserted, because "no file outside" is also
   * what refusing to speak at all would produce. */
  const EVIL = "../climbed";
  const TEXT = "this reply arrived with a msgId that is a path";
  await onSpeak(client.sock, { t: "speak", text: TEXT, msgId: EVIL });
  const say = await untilSay(TEXT);

  for (const outside of [join(core.dir, "staging", "climbed.mp3"),
    join(audioDirFor(String(say.msgId)), "..", "climbed.mp3")]) {
    expect(await Bun.file(outside).exists(),
      `a speak frame carrying msgId "${EVIL}" wrote the TTS bytes to ${outside}, one directory ` +
      "above the audio dir. safeCid (logbook.ts) is the filter clipOnDisk already applies to " +
      "this exact field on the read side.").toBe(false);
  }

  /* AND THE REPLY STILL ARRIVED, which is the half a rejection would fail. */
  expect(client.of("chat").some((f) => f.role === "claude" && f.text === TEXT),
    "the reply was dropped because its msgId was unusable. The id is bookkeeping and the " +
    "words are the message.").toBeTruthy();
  expect(say.msgId,
    "the engine broadcast the traversal string back as the clip's id, so every device now " +
    `fetches /audio/${EVIL}.mp3`).not.toBe(EVIL);
  expect(String(say.msgId),
    "the substituted id is not from safeCid's alphabet either, so it is one more raw string " +
    "on its way into a path").toMatch(/^[A-Za-z0-9_.-]{1,64}$/);
  expect(await Bun.file(audioPath(String(say.msgId), "audio/mpeg")).exists(),
    "the announced clip is not where the substituted id says it is, so the id was cleaned up " +
    "for the wire and not for the write").toBe(true);
});

test("a well formed msgId reaches the page unchanged", async () => {
  /* THE OTHER HALF, and without it the test above passes on an engine that
   * throws every caller's msgId away. engine/mcp/src/server.ts mints one per reply and
   * prints it back to the agent ("spoke (msgId: ...)"), which is only worth
   * anything if it names the clip the page actually got. */
  const MINE = crypto.randomUUID(); // exactly what the MCP sends
  const TEXT = "this one brought a perfectly good id";
  await onSpeak(client.sock, { t: "speak", text: TEXT, msgId: MINE });
  const say = await untilSay(TEXT);
  expect(say.msgId,
    "the engine replaced a msgId that had nothing wrong with it. The MCP told the agent this " +
    "id, and a grep on it now crosses into nothing.").toBe(MINE);
  // ...and the ack the tool waits on names the WIRE id, which is what it is keyed on
  expect(client.last("said")!.msgId).toBe(MINE);
});

test("a spoken reply's own bubble arrives before the clip is announced", async () => {
  /* A `say` names a msgId. The bubble that plays it is created by `chat` and by
   * nothing else, so a say that arrives first names a message the page does not
   * have, and the page has to work out which bubble it meant -- which it did by
   * comparing the WORDS (store.ts, the backwards walk).
   *
   * That is a real defect and it is his: 2026-08-05, pane w9:p4, an agent wrote
   * "Understood. No actions, no notes, nothing written from this." and spoke the
   * same sentence five seconds later. The chat log has the two records right --
   * the written one with no msgId, the spoken one carrying 228a0ace and
   * durationS 4 -- and the app still put the play button on the WRITTEN bubble,
   * because when the say landed that was the newest claude bubble with those
   * words and no msgId. */
  const TEXT = "Understood. No actions, no notes, nothing written from this.";
  await onSpeak(client.sock, { t: "speak", text: TEXT });
  await untilSay(TEXT);

  const chatAt = client.frames.findIndex((f) =>
    f.t === "chat" && f.role === "claude" && f.text === TEXT);
  const sayAt = client.frames.findIndex((f) => f.t === "say" && f.text === TEXT);
  expect(sayAt, "the spoken reply was never announced").toBeGreaterThan(-1);
  expect(chatAt, "the spoken reply never arrived as a message").toBeGreaterThan(-1);
  expect(chatAt, "the clip was announced before the message it belongs to existed. A page " +
    "hearing `say` first has no bubble carrying this msgId, which is exactly when it falls " +
    "back to finding one by its text -- and the words of a spoken reply are not unique.")
    .toBeLessThan(sayAt);

  // and the frame that arrives first is the one that carries the identity
  expect(client.frames[chatAt].msgId,
    "the message arrived first but without the msgId, so being first bought nothing: there " +
    "is still no bubble the `say` can be matched to by anything but its words.")
    .toBe(client.frames[sayAt].msgId);
});

/** The `say` frame for one reply, once its clip exists. */
async function untilSay(text: string): Promise<Record<string, unknown>> {
  await until(() => client.of("say").some((f) => f.text === text),
    { what: `the say frame for ${JSON.stringify(text.slice(0, 24))}` });
  return client.of("say").find((f) => f.text === text)!;
}
