/* ONE message, SEVERAL attachments.
 *
 * WHY THIS FILE EXISTS
 *
 * `ChatMsg.upload` was one optional record and the delivery path took one, so a
 * composition of three clips and a caption left as three messages with the
 * caption on the first. `uploads` is the plural form, added BESIDE the singular
 * rather than replacing it, and that pair is what everything here is about.
 *
 * WHAT IS ACTUALLY AT RISK, and it is not the happy path:
 *
 *   1. THE SWEEP. Staging is bounded by reference-counting what the chat log
 *      points at, and that count used to be `m.upload?.uploadId`. A
 *      plural-aware writer with a singular-aware sweep deletes attachments two
 *      through four out from under a live message: the bubble 404s and the path
 *      the agent was handed is gone. This is the one that loses his audio, so it
 *      is first.
 *   2. THE OLD SHAPE. Every message already on disk has the singular field, and
 *      CHAT_KEEP is Infinity, so those entries outlive every version of this
 *      code. The fixture below is written BY HAND in the old shape rather than
 *      generated by the new code, or it would prove nothing.
 *   3. ONE MESSAGE. Item 90: the session is handed one message with all its
 *      blocks, never a piece at a time. What the agent receives is what was
 *      SUBMITTED into its pane, so that is what is counted.
 *   4. ORDER. Attachment three must not arrive as attachment one, in the text
 *      the agent gets or in the message the app replays.
 *   5. ALL OR NOTHING. A message that did not land leaves nothing behind to
 *      reconcile: no bubble, no delivery, and no reference pinning its files in
 *      a directory that is supposed to be able to reclaim them.
 *
 * The screen classification and the guard that decides whether to type at all
 * are in delivery-guard.test.ts.
 *
 * POST /upload is the REAL media route on a port-0 Bun.serve over this wiring's
 * own uploads store, so an attachment gets here the way one really does.
 *
 *   bun test agent-engine/src/chat/multipart.test.ts
 */

import { test, expect, beforeAll, afterAll, afterEach } from "bun:test";
import { readdir, unlink, utimes, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { onUtterance } from "./deliver.ts";
import { onAttach } from "./attach.ts";
import { mediaRoutes } from "../routes/media.ts";
import { stagingUploadsDir, agentUploadsDir } from "../storage/datadir.ts";
import { UPLOAD_KEEP } from "./uploads.ts";
import type { UploadRec } from "./chatmsg.ts";
import { wireCore, type WireCore, type WireCoreOpts, wireId } from "../test-utils/wire-core.ts";
import { serveRoutes, type ServedRoutes } from "../test-utils/serve-routes.ts";
import { PANE, defaultSessionIdOf } from "../test-utils/fake-herdr.ts";
/* The harness id the fake herdr reports for PANE: what the disk records
 * (meta.json sessionId, the chat log) are keyed by, never the pane id. */
const PANE_SID = defaultSessionIdOf(PANE);
import { seedAgent, readChatLog } from "../test-utils/builders.ts";
import { until, untilValue } from "../test-utils/wait.ts";

/* The settle between a delivery's text and its enter, shortened at file scope.
 * It is a real pause a real TUI needs (see adapters/mux-adapter.ts), so there is
 * no logical clock to advance; the only thing this changes is how long a file
 * with a dozen deliveries in it spends waiting. */
const priorSettle = process.env.DELIVER_SETTLE_MS;
beforeAll(() => { process.env.DELIVER_SETTLE_MS = "5"; });
afterAll(() => {
  if (priorSettle === undefined) delete process.env.DELIVER_SETTLE_MS;
  else process.env.DELIVER_SETTLE_MS = priorSettle;
});

let core: WireCore | null = null;
let http: ServedRoutes | null = null;
afterEach(async () => {
  http?.stop();
  http = null;
  await core?.stop();
  core = null;
});

/** The delivery wiring, its pane reconciled, plus the real media routes over
 *  its uploads store so POST /upload is the shipped code. */
async function rig(o: WireCoreOpts = {}): Promise<WireCore> {
  core = await wireCore({ with: ["delivery"], ...o });
  await until(() => core!.sessions.size === 1, { what: "the pane to reconcile" });
  http = serveRoutes({ groups: [mediaRoutes], ctx: { uploads: core.uploads! } });
  return core;
}

/* SEEDING NEEDS THE DIRS BEFORE THE BOOT THAT READS THEM.
 *
 * A chat log written by an older engine has to be on disk before loadSessionState
 * runs, and wireCore makes its tmp dir inside wireCore(). So: wire the BASE
 * layer (dirs, herdr, adapter, and not one engine module), write the fixture, and
 * reset() into the real layers -- which re-boots in the SAME dirs. That is what
 * "an engine starting on a data dir that already has something in it" is. */
async function rigOverSeed(seed: (root: string) => Promise<void>,
                           o: WireCoreOpts = {}): Promise<WireCore> {
  core = await wireCore({ with: [] });
  await seed(core.root);
  await core.reset({ with: ["delivery"], ...o });
  await until(() => core!.sessions.size === 1, { what: "the seeded pane to reconcile" });
  http = serveRoutes({ groups: [mediaRoutes], ctx: { uploads: core.uploads! } });
  return core;
}

type Upload = UploadRec & { durationS?: number };

/** POST /upload, the way the composer stages a file. */
async function stage(name: string, body: string,
                     headers: Record<string, string> = {}): Promise<Upload> {
  const res = await http!.fetch("/upload", {
    method: "POST",
    headers: { "content-type": "text/plain", "x-filename": name, ...headers },
    body,
  });
  if (!res.ok) throw new Error(`POST /upload ${name}: HTTP ${res.status}`);
  return (await res.json()) as Upload;
}

/* MORE STAGED-AND-NEVER-SENT FILES THAN THE CAP ALLOWS, so a sweep MUST run.
 *
 * Written straight into the staging dir: debris is debris however it got there,
 * and 205 round trips through a route proves nothing extra.
 *
 * EVERY ONE OF THEM IS STAMPED, and that is not tidiness. trimUploads keeps the
 * NEWEST 200 by mtime, and a file written in the same millisecond as another has
 * the same mtime, so the sort between them is whatever the sort happens to do.
 * Left unstamped, the files a test is asking about could land inside the kept
 * 200 by luck and the test would pass or fail on timer resolution. `from`
 * anchors the run: each file is stamped one millisecond later than the last, so
 * the order is total and the boundary is exactly where the test put it. */
async function debris(n = UPLOAD_KEEP + 5, from = Date.now()): Promise<void> {
  const dir = stagingUploadsDir() + "/";
  for (let i = 1; i <= n; i++) {
    const id = `${String(i).padStart(8, "0")}-eeee-4eee-8eee-eeeeeeeeeeee`;
    const path = join(dir, `${id}-debris.txt`);
    await writeFile(path, `staged ${i}, never sent`);
    const t = new Date(from + i);
    await utimes(path, t, t);
  }
}

const stagedNames = () => readdir(stagingUploadsDir());
/** The agent's own uploads dir, keyed by the STABLE agent id off the live
 *  session rather than off meta.json: the meta save is debounced, so reading it
 *  from disk answers "not yet" for a message that has already been delivered. */
const adoptedNames = (c: WireCore) =>
  readdir(agentUploadsDir(c.byHandle(PANE)!.agentId)).catch(() => [] as string[]);

/** The user bubble the engine broadcast for this text, once it exists. */
const bubbleFor = (cl: { of(t: string): Record<string, any>[] }, text: string) =>
  cl.of("chat").find((f) => f.role === "user" && f.text === text);

/* ------------------------------------------------------------------ THE SWEEP
 *
 * Four attachments on one message, then more debris than the cap allows, so the
 * sweep has to run and has to spare all four. Against the singular reference
 * count this fails on files two, three and four while the first one survives,
 * which is exactly the shape that would have shipped unnoticed: the bubble still
 * shows something. */
test("the sweep spares every file a multi-attachment message points at", async () => {
  const c = await rig();
  const cl = c.client();

  const sent = [
    await stage("one.txt", "first"),
    await stage("two.txt", "second"),
    await stage("three.txt", "third"),
    await stage("four.txt", "fourth"),
  ];
  await onUtterance(cl.sock, { id: wireId(PANE), text: "all four of these", uploads: sent });

  /* The premise, checked rather than assumed: if the message never reached the
   * chat log then nothing references anything and the assertions below would
   * pass against an engine that did nothing at all. */
  const accepted = c.logs.find((l) => l.event === "utterance.accepted");
  expect(accepted, "the engine never accepted the utterance carrying the attachments").toBeDefined();
  for (const u of sent) {
    expect(String(accepted!.fields.upload),
      `the accepted line does not name ${u.name}`).toContain(u.uploadId);
  }

  await debris();
  await c.uploads!.trimUploads("test");
  const left = await stagedNames();
  expect(left.length, `nothing bounds staging/uploads: ${left.length} files`)
    .toBeLessThanOrEqual(UPLOAD_KEEP);

  /* The four sent files were ADOPTED into the agent's own uploads dir the moment
   * their message landed, which is what puts them out of the sweep's reach BY
   * CONSTRUCTION. */
  const adopted = await adoptedNames(c);
  expect(
    sent.filter((u) => !adopted.some((f) => f.startsWith(`${u.uploadId}-`))).map((u) => u.name),
    "an attachment a live message points at is not in the agent's uploads dir; the bubble " +
    "that shows it now 404s and the path the agent was handed is gone",
  ).toEqual([]);

  // and every one of them still serves, which is what the bubble needs
  for (const u of sent) {
    expect((await http!.fetch(`/upload/${u.uploadId}`)).status, `${u.name} no longer serves`).toBe(200);
  }
});

/* THE SWEEP READS A UNION, BECAUSE THE SWEEP IS THE ONE THAT DELETES.
 *
 * `attachmentsOf` answers "what does this message show", so a present `uploads`
 * wins and `upload` is ignored as the copy of its first entry it is meant to be.
 * When the two DISAGREE -- a half-written message, a bundle that set one and not
 * the other -- `upload` names a file the ordered list does not, an older app
 * bundle draws exactly that file, and reading the list alone sweeps it away. */
test("a message whose upload disagrees with uploads[0] keeps both files", async () => {
  const listedId = "00000000-cccc-4ccc-8ccc-cccccccccccc";
  const singularId = "00000000-dddd-4ddd-8ddd-dddddddddddd";
  const listedName = `${listedId}-listed.txt`;
  const singularName = `${singularId}-disagrees.txt`;
  const old = Date.now() - 100_000;

  const c = await rigOverSeed(async (root) => {
    /* BOTH referenced files sit in STAGING -- an engine that crashed between the
     * log write and the adoption looks exactly like this -- so the sweep runs
     * over them and must still spare what any chat log references. */
    const dir = stagingUploadsDir() + "/";
    await writeFile(join(dir, listedName), "in the ordered list");
    await writeFile(join(dir, singularName), "only on the singular field");
    const stamp = new Date(old);
    await utimes(join(dir, listedName), stamp, stamp);
    await utimes(join(dir, singularName), stamp, stamp);
    const rec = (id: string, name: string) => ({
      uploadId: id, name, mime: "text/plain", size: 20,
      path: join(dir, `${id}-${name}`), image: false,
    });
    await seedAgent(root, PANE_SID, [{
      id: wireId(PANE), role: "user", text: "the two fields disagree", ts: 1000,
      // exactly the shape a half-written message has: the singular field is NOT
      // a copy of uploads[0]
      upload: rec(singularId, "disagrees.txt"),
      uploads: [rec(listedId, "listed.txt")],
    }]);
  });

  expect(
    c.byHandle(PANE)!.chat.map((m) => m.text),
    "the engine restored no chat log, so nothing referenced anything and the assertions " +
    "below would pass against an engine that read nothing",
  ).toContain("the two fields disagree");

  await debris(UPLOAD_KEEP + 10, old);
  await c.uploads!.trimUploads("test");

  const left = await stagedNames();
  expect(left.length, "nothing swept, so this proves nothing")
    .toBeLessThanOrEqual(UPLOAD_KEEP + 2);
  expect(left, "the file in the ordered list was swept").toContain(listedName);
  expect(
    left,
    "the file named only by the singular `upload` was swept, while an older app bundle still " +
    "draws exactly that file: the delete side must read a union of both fields",
  ).toContain(singularName);
});

/* THE OLD SHAPE, WRITTEN BY HAND.
 *
 * A chat entry as every version before this one wrote it: one `upload` record,
 * no `uploads` anywhere. It has to survive the boot sweep and it has to reach a
 * PAGE with its attachment intact, because that is what rendering a bubble
 * consists of on this side. */
test("a chat log entry in the old single-upload shape still reads and still renders", async () => {
  const keptId = "00000000-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
  const keptName = `${keptId}-legacy.pdf`;
  const AG = "ag-legacyshape000001";

  const c = await rigOverSeed(async (root) => {
    const uploads = agentUploadsDir(AG);
    await Bun.write(join(uploads, keptName), "written by an older engine");
    await seedAgent(root, PANE_SID, [{
      id: wireId(PANE), role: "user", text: "the old shape", ts: 1000,
      upload: {
        uploadId: keptId, name: "legacy.pdf", mime: "application/pdf",
        size: 26, path: join(uploads, keptName), image: false,
      },
    }], { agentId: AG });
  }, { with: ["delivery", "frames"] });

  const cl = c.client();
  onAttach(cl.sock, { id: wireId(PANE), since: 0 });

  // the replay rides inside the attach answer's pages, not as {t:'chat'} frames
  const bubble = await untilValue(() => {
    for (const p of cl.last("attach-ok")?.pages ?? []) {
      const m = p.messages.find((x: any) => x.role === "user" && x.text === "the old shape");
      if (m) return m;
    }
    return undefined;
  }, { what: "the old-shape message to replay inside an attach page" });

  expect(bubble.upload?.uploadId,
    "the singular `upload` field was dropped on the way to the page, so a message written " +
    "before this change renders with no attachment").toBe(keptId);
  expect(bubble.upload?.name).toBe("legacy.pdf");

  // and the file itself was not swept out from under it
  await c.uploads!.trimUploads("test");
  expect(await readdir(agentUploadsDir(AG)),
    "the old-shape message's file is gone").toContain(keptName);
  expect((await http!.fetch(`/upload/${keptId}`)).status).toBe(200);
});

/* ONE MESSAGE, AND IN ORDER (items 90 and 29).
 *
 * `submitted` is what the pane actually received, which is the text an agent
 * reads: three attachments must make that ONE longer line, not three lines and
 * not three deliveries. The order is asserted twice, because the agent's copy
 * and the app's copy are two different pieces of code and either could reverse. */
test("the agent receives one message carrying three attachments, in order", async () => {
  const c = await rig();
  const cl = c.client();

  const sent = [
    await stage("alpha.txt", "a"),
    await stage("beta.txt", "b"),
    await stage("gamma.txt", "c"),
  ];
  await onUtterance(cl.sock, { id: wireId(PANE), text: "three files", uploads: sent });

  const bubble = bubbleFor(cl, "three files");
  expect(bubble, "the message never came back to the page").toBeDefined();

  expect(
    c.submitted.length,
    `the session was handed ${c.submitted.length} messages for one composition: ` +
    JSON.stringify(c.submitted.map((s) => s.text)),
  ).toBe(1);

  const delivered = c.submitted[0].text;
  /* The delivered paths are the ADOPTED copies (agents/<agentId>/uploads/...),
   * so the assertion keys on the sweep-proof `<uploadId>-<name>` tail that
   * survives the move. */
  for (const u of sent) {
    expect(delivered, `${u.name} never reached the agent: ${delivered}`)
      .toContain(`${u.uploadId}-${u.name}`);
  }
  const positions = sent.map((u) => delivered.indexOf(`${u.uploadId}-${u.name}`));
  expect(positions, `the attachments reached the agent out of order: ${delivered}`)
    .toEqual([...positions].sort((a, b) => a - b));
  expect(delivered, "the caption did not ride along with the attachments").toContain("three files");
  // it is ONE delivery, so exactly one enter went in behind it
  expect(c.herdr.keys.filter((k) => k.keys.includes("enter")).length,
    "several attachments became several deliveries").toBe(1);

  // and the app's copy carries all three, in the same order
  expect(
    (bubble!.uploads ?? []).map((u: Upload) => u.name),
    `the replayed message does not carry all three in order: ${JSON.stringify(bubble!.uploads)}`,
  ).toEqual(["alpha.txt", "beta.txt", "gamma.txt"]);
  // `upload` still holds the first, so a bundle that predates `uploads` draws
  // one attachment rather than none
  expect(bubble!.upload?.name).toBe("alpha.txt");
});

/* Every attached path is handed over as its own bracketed block, in composer
 * order, and the caption follows. Narrow `Injection.uploads` back to a single
 * upload and this fails on the count: four files become one, silently. */
test("the pane is handed every attached path as its own block, in composer order", async () => {
  const c = await rig();
  const cl = c.client();

  const sent = [
    await stage("one.txt", "first"),
    await stage("two.txt", "second"),
    await stage("three.txt", "third"),
    await stage("four.txt", "fourth"),
  ];
  await onUtterance(cl.sock, { id: wireId(PANE), text: "all four of these", uploads: sent });

  const delivered = c.submitted[0]!.text;
  /* Each path is its OWN bracketed block, and each block names the ADOPTED copy
   * in the agent's uploads dir. Keyed on the `<uploadId>-<name>` tail, which is
   * the part that survives the move out of staging. */
  const blocks = [...delivered.matchAll(/\[attached (?:file|image): ([^\]]+)\]/g)].map((m) => m[1]);
  expect(
    blocks.map((p) => p.slice(p.lastIndexOf("/") + 1)),
    `the pane was not given every attached path, in order: ${delivered}`,
  ).toEqual(sent.map((u) => `${u.uploadId}-${u.name}`));
  expect(blocks.every((p) => p.includes("/agents/")),
    `a delivered path is not the engine's adopted copy: ${delivered}`).toBe(true);
  expect(delivered.startsWith("TEXT: "), `a typed message is tagged TEXT: ${delivered}`).toBe(true);

  const bubble = bubbleFor(cl, "all four of these")!;
  expect(
    (bubble.uploads ?? []).map((u: Upload) => u.name),
    "the message he composed arrived with fewer attachments than he attached: the delivery " +
    "path carried one where it was handed four",
  ).toEqual(["one.txt", "two.txt", "three.txt", "four.txt"]);
  expect(bubble.upload?.name).toBe("one.txt");
});

/* ALL OR NOTHING AT THIS BOUNDARY (item 89).
 *
 * The engine commits every part of a message or none of them; there is one
 * failure mode, "it did not land", and the app's answer is to send it again. So
 * the thing to assert is that a message which did not land left NOTHING behind:
 * no bubble, no delivery to the agent, and no reference holding its files in a
 * directory that is supposed to be able to reclaim them.
 *
 * Produced with a session id this engine has never heard of, which is the real
 * shape of it: the app reached the wrong engine, or the pane went away between
 * the staging and the send. */
test("a message that did not land commits no part of itself", async () => {
  const c = await rig();
  const cl = c.client();

  const sent = [
    await stage("lost-one.txt", "a"),
    await stage("lost-two.txt", "b"),
  ];
  await onUtterance(cl.sock, { id: wireId("w9:p99"), text: "nowhere to go", uploads: sent });

  expect(
    c.logs.some((l) => l.event === "utterance.dropped"),
    "the engine neither delivered the message nor said it dropped it",
  ).toBe(true);
  expect(
    cl.of("chat").filter((f) => f.text === "nowhere to go"),
    "half a message reached the chat log",
  ).toEqual([]);
  expect(c.herdr.texts, "part of a message that did not land was typed into a session anyway")
    .toEqual([]);
  expect(c.submitted, "an agent received part of a message that did not land").toEqual([]);

  /* And nothing is holding those files: an uncommitted message must not leave
   * its uploads referenced for ever, or a failed send would pin the directory it
   * is the app's job to retry into. */
  await debris();
  await c.uploads!.trimUploads("test");
  const left = await stagedNames();
  expect(
    sent.every((u) => !left.some((f) => f.startsWith(`${u.uploadId}-`))),
    "the files of a message that never landed are being kept alive as though it had",
  ).toBe(true);
});

/* One attachment is written in the new PAIR: `uploads` is the list, `upload` is
 * a copy of its first entry. Old singular-only rows stay a reader concern. */
test("one attachment is written in the multi-attachment shape", async () => {
  const c = await rig();
  const cl = c.client();

  const only = await stage("solo.txt", "just the one");
  await onUtterance(cl.sock, { id: wireId(PANE), text: "have a look", upload: only });

  const bubble = bubbleFor(cl, "have a look");
  expect(bubble, "the single-attachment message never came back").toBeDefined();
  expect(bubble!.upload?.uploadId).toBe(only.uploadId);
  expect(bubble!.uploads?.length).toBe(1);
  expect(bubble!.uploads?.[0]?.uploadId).toBe(only.uploadId);

  expect(c.submitted.length).toBe(1);
  const line = c.submitted[0].text;
  expect(line).toContain("[attached file: ");
  // the delivered path is the ADOPTED copy in the agent's uploads dir
  expect(line).toContain(`/uploads/${only.uploadId}-solo.txt] have a look`);
  expect(line).toContain("/agents/");
});

/* AND THE FILE IS STILL THERE AT SEND, OR THE MESSAGE FAILS.
 *
 * Staging protects nothing: an upload is spared by the sweep only once a message
 * references it, so a file held in the composer is debris that newer uploads
 * evict. A record naming a path that is gone used to be accepted, logged, drawn
 * in the bubble and handed to the agent as a real path to open. Newly reachable,
 * because a composition now holds several of them at once. */
test("an attachment whose file has gone fails the whole message", async () => {
  const c = await rig();
  const cl = c.client();

  const here = await stage("still-here.txt", "present");
  const gone = await stage("swept-away.txt", "gone");
  /* The FILE is removed, not just the path the client wrote: the engine ignores
   * a client path and looks the uploadId up, so rewriting `path` to a missing
   * name would still find the staged file. */
  await unlink(gone.path);

  await onUtterance(cl.sock, { id: wireId(PANE), cid: "c-gone", text: "one of these is missing", uploads: [here, gone] });

  /* The failure lands on the row (F2): a send-failed on the cid, not a grey
   * notice bubble. The agent must not get a path that opens nothing while the
   * user is told it was sent. */
  const failed = cl.of("send-failed").map((f) => ({ cid: String(f.cid), reason: String(f.reason) }));
  expect(failed, "a message naming a file that is not on disk was accepted silently").toHaveLength(1);
  expect(failed[0].cid).toBe("c-gone");
  expect(failed[0].reason, "the failure does not say which file is missing").toContain("swept-away.txt");
  expect(failed[0].reason).toMatch(/no longer on the engine/);
  expect(cl.of("chat").filter((f) => f.role === "claude"),
    "the failure was reported as a broadcast notice bubble rather than on the sender's row").toEqual([]);

  expect(
    cl.of("chat").filter((f) => f.role === "user" && f.text === "one of these is missing"),
    "the message was written to the chat log anyway, so the failure is not whole-message",
  ).toEqual([]);
  expect(c.submitted, "the good half of the message was delivered to the agent: a partial send")
    .toEqual([]);
  expect(c.herdr.texts, "the good half was typed at the pane").toEqual([]);
});

/* A FORGED PATH NEVER BECOMES A DELIVERED PATH, on the multi-attachment shape.
 * The narrow security case has its own file (attachment-path.test.ts); this is
 * the composition-sized version of it, where one good record and one forge ride
 * the same message. */
test("a forged record in a composition is dropped and the real one still goes", async () => {
  const c = await rig();
  const cl = c.client();

  const real = await stage("notes.txt", "the real file");
  const forged: Upload = {
    uploadId: "00000000-0000-4000-8000-000000000000", name: "secret.txt",
    mime: "text/plain", size: 20, path: "/etc/passwd", image: false,
  };
  await onUtterance(cl.sock, { id: wireId(PANE), text: "one real, one forged", uploads: [real, forged] });

  const bubble = bubbleFor(cl, "one real, one forged")!;
  expect(bubble.uploads?.length, "the forged record survived onto the bubble").toBe(1);
  expect(bubble.uploads?.[0]?.uploadId).toBe(real.uploadId);
  const delivered = c.submitted[0].text;
  expect(delivered, `the agent was handed /etc/passwd: ${delivered}`).not.toContain("/etc/passwd");
  expect(delivered).toContain(`${real.uploadId}-notes.txt`);
  expect(c.logs.some((l) => l.event === "utterance.attach-dropped"),
    "the engine never logged that it dropped the forged attachment").toBe(true);
});

/* ------------------------------------------------------- HOW LONG THE CLIP IS
 *
 * A clip recorded in a browser carries no duration in its container, so only the
 * recorder knows and only at record time. If the engine drops the number on the
 * way past, a sent voice block has no length, no clock and a dead seek the
 * moment the page reloads or another device replays the history -- and nothing
 * downstream can recover it. */
test("a recording's length survives the upload, the send and the replay", async () => {
  const c = await rig();
  const cl = c.client();

  // the app posts the clip with the length it measured while recording
  const rec = await stage("voice-1.webm", "clip bytes",
    { "content-type": "audio/webm", "x-duration-s": "12" });
  expect(rec.durationS, "POST /upload dropped the length the recorder measured").toBe(12);

  await onUtterance(cl.sock, { id: wireId(PANE), text: "listen to this", uploads: [rec] });
  expect(bubbleFor(cl, "listen to this")!.upload?.durationS,
    "the length was lost between the send frame and the bubble, so the sent voice block has " +
    "no clock and a dead seek bar").toBe(12);

  // and it is on disk, which is what a reload and another device read
  const stored = await untilValue(async () =>
    (await readChatLog(c.root, PANE_SID)).find((r: any) => r.text === "listen to this"),
    { what: "the message to reach the persisted chat log" }) as any;
  expect(stored.upload?.durationS,
    "the length is not in the chat log, so it is gone after a reload").toBe(12);
});

test("an attachment with no length still sends, and nonsense never gets stored", async () => {
  const c = await rig();
  const cl = c.client();

  const plain = await stage("notes.txt", "not a recording");
  expect(plain.durationS, "a file that is not a recording was given a length").toBeUndefined();

  // a client sending rubbish: none of it may reach the log
  await onUtterance(cl.sock, { id: wireId(PANE), text: "with junk", uploads: [
    { ...plain, durationS: -4, fromPage: { label: "submit", page: "x.html" } },
  ] });

  const bad = bubbleFor(cl, "with junk")!;
  expect(bad.upload?.durationS, "a negative length was stored and will draw a broken bar")
    .toBeUndefined();
  /* AND NOTHING ELSE ON THE RECORD WAS EATEN. Sanitising one field by rebuilding
   * the object is how `fromPage` would quietly disappear; this is the assertion
   * that keeps the fix a spread. */
  expect(bad.upload?.fromPage, "an unrelated field was dropped while cleaning the length")
    .toEqual({ label: "submit", page: "x.html" });
});
